### ISSUE TITLE
Add support for VBSP v22

### ISSUE THREAD

**Issue by TheRogueArchivist** [mnadareski/HLLibSharp#3]
Trying to extract VBSP files found in the game INFRA prints the following:
````
Invalid VBSP version (v22): you have a version of a VBSP file that HLLib does not know how to read. Check for product updates.
Package could not be opened!
````

**Comment by mnadareski** [comment]
Unsupported by HLLib/HLExtract. Not adding support for it because I honestly don't know version differences.
